### ISSUE TITLE
Decommission this repository

### ISSUE THREAD

**Issue by WilliamJamieson** [asdf-format/asdf-table-schemas#22]
This repository no-longer serves any purpose as all the schema information contained within it already exists in `asdf-standard`. It only existed to support asdf-format/asdf-standard#341, which was part of the attempt to split parts of `asdf-standard` off. Since asdf-format/asdf-standard#341 has been abandoned the purpose of this repository is has been lost. Moreover, the packaged contained in this repository has never been published.

**Comment by braingram** [comment]
Thanks for raising this issue. The plan should be discussed. However, I don't believe the current consensus is that the effort to break up the standard has been abandoned by ASDF developers. I'm closing this issue to not mislead any potential users of this package.
